#include <iostream>
#include "discord_rpc.h"
#include "discord_register.h"
#include "pch.h"
#include <ctime>
#include <Windows.h>
#include <windows.h>
#include <future>
#include <string>




/*

__________                    ___________
\____    /___________  ____   \__    ___/_  _  ______
  /     // __ \_  __ \/  _ \    |    |  \ \/ \/ /  _ \
 /     /\  ___/|  | \(  <_> )   |    |   \     (  <_> )
/_______ \___  >__|   \____/    |____|    \/\_/ \____/
		\/   \/

Copyright (C) 2019 Justin Carlson

This piece of software is witheld under the Zero Two license
which is basically just the GNU public licence. But you know...
with more DARLING!!!


This program is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by 
the Free Software Foundation, either version 3 of the License, or (at your option) 
any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
See the GNU General Public License for more details.

You can find more details here: https://www.gnu.org/licenses/gpl-3.0.en.html

⣿⣿⣿⣿⢡⣿⢇⠄⢨⣶⣿⣿⣿⣿⣿⣿⣷⣶⣭⣟⡿⠁⣸⣿⣿⣿⣿⣧⢣⢧
⣿⣿⣿⡏⣿⢣⠾⣤⠞⣡⣶⣶⣶⣶⣬⣭⣽⣛⠻⣿⡇⠄⡛⢿⣿⣿⣿⣿⡞⣎
⣿⣿⣸⣁⣵⣿⣶⠎⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⢱⡼⢼⣧⡹⣿⣿⣿⡇⣿
⠄⣩⣵⣿⣿⢹⣿⢃⢳⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢳⣿⣧⣝⢻⡝⣿⣿⡇⣿
⠃⣾⠃⣿⡏⢇⣮⣟⠸⡇⣿⣿⢸⠿⣿⣿⣤⢿⣿⣿⢸⢹⡆⡟⣸⣿⡟⣿⡇⣿
⢰⣿⠄⣿⡇⡜⠛⠛⠿⢤⢹⣿⣼⢀⣿⡏⠿⠄⣿⠟⣰⣦⢧⢱⣿⣿⠳⣿⠃⣿
⡜⣿⡆⣿⡇⣿⣿⣷⣶⣾⣦⣄⣧⣸⡸⢧⣿⡨⠩⠦⠿⠿⡼⢸⣿⡿⣄⢈⡆⢸
⠹⣿⡇⣿⡇⣿⣿⣿⣿⣿⣿⣿⢻⣿⣿⣿⣶⣶⣶⣶⣶⣶⡆⣿⣿⢇⡟⣼⡧⣫
⠄⢹⡇⣿⡇⣿⣿⣿⣿⣿⣿⣧⣤⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⣿⣿⢘⣾⣿⢷⠋
⠄⠈⡇⣿⡇⣹⣿⣿⣿⣿⣿⣧⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢣⣿⡟⣾⣿⣿⠄⠄
⠄⠄⢠⣿⡇⣷⠘⢿⣿⣧⡲⣾⣭⣭⣿⣒⠊⣹⣿⣿⡿⠁⣸⣿⡇⣿⣿⡏⡇⠄
⠄⠄⠄⣿⡇⣿⠄⠄⠙⢿⣿⣷⣶⣶⣶⣾⣿⣿⠟⠋⠄⠄⣿⣿⢳⣿⣿⢹⡇⠄
⠄⠄⠄⠘⣿⢸⢰⣆⠄⠄⠙⠻⣿⡿⠟⠛⠉⠄⠄⠄⠄⠄⣿⡟⣼⣿⢏⣿⢧⣷


*/



using namespace std;

void startWowClassic();
void handleCustomPresence();
void asynchronousUpdating();
string getClassFromNumber(int i);
string getRaceFromNumber(int i);
string getLocationFromNumber(int number);

char currentLocation[50];
char currentLevel[50];
char currentRace[50];
char currentClass[50];
long long startTime = time(0);

DWORD playerBase = 0x00b05d38;
DWORD locationOffset = 0x00b6e5d0;
DWORD levelOffset = 0x00BC7624;
DWORD raceOffset = 0x00b6e6b0;
DWORD classOffset = 0x10;




int indices[2000] = {
1,
2,
3,
4,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
21,
22,
23,
24,
25,
26,
28,
30,
32,
33,
34,
35,
36,
37,
38,
40,
41,
42,
43,
44,
45,
46,
47,
49,
51,
53,
54,
55,
56,
57,
59,
60,
61,
62,
63,
64,
68,
69,
70,
71,
72,
73,
74,
75,
76,
77,
80,
85,
86,
87,
88,
89,
91,
92,
93,
94,
95,
96,
97,
98,
99,
100,
101,
102,
103,
104,
105,
106,
107,
108,
109,
111,
113,
115,
116,
117,
118,
120,
121,
122,
123,
125,
126,
127,
128,
129,
130,
131,
132,
133,
134,
135,
136,
137,
138,
139,
141,
142,
143,
144,
145,
146,
147,
148,
149,
150,
151,
152,
153,
154,
155,
156,
157,
158,
159,
160,
161,
162,
163,
164,
165,
166,
167,
168,
169,
170,
172,
173,
186,
188,
189,
190,
192,
193,
195,
196,
197,
198,
199,
200,
201,
202,
203,
204,
205,
207,
208,
209,
211,
212,
213,
214,
215,
219,
220,
221,
222,
223,
224,
225,
226,
227,
228,
229,
230,
231,
232,
233,
235,
236,
237,
238,
239,
240,
241,
242,
243,
244,
245,
246,
247,
249,
250,
251,
252,
253,
254,
255,
256,
257,
258,
259,
260,
261,
262,
263,
264,
265,
266,
267,
268,
269,
271,
272,
275,
276,
277,
278,
279,
280,
281,
282,
283,
284,
285,
286,
287,
288,
289,
290,
293,
294,
295,
297,
298,
299,
300,
301,
302,
303,
305,
306,
307,
308,
309,
310,
311,
312,
313,
314,
315,
316,
317,
318,
320,
321,
322,
323,
324,
325,
326,
327,
328,
330,
331,
332,
333,
334,
335,
336,
337,
338,
339,
340,
341,
342,
343,
344,
345,
346,
347,
348,
349,
350,
351,
352,
353,
354,
355,
356,
357,
358,
359,
360,
361,
362,
363,
364,
365,
366,
367,
368,
369,
370,
371,
372,
373,
374,
375,
377,
378,
379,
380,
381,
382,
383,
384,
385,
386,
387,
388,
390,
391,
392,
393,
396,
397,
398,
399,
400,
401,
403,
404,
405,
406,
408,
409,
410,
411,
412,
413,
414,
415,
416,
417,
418,
419,
420,
421,
422,
424,
425,
426,
427,
428,
429,
430,
431,
432,
433,
434,
435,
436,
437,
438,
439,
440,
441,
442,
443,
444,
445,
446,
447,
448,
449,
450,
452,
453,
454,
455,
456,
457,
458,
459,
460,
461,
463,
464,
465,
466,
467,
468,
469,
471,
472,
473,
477,
478,
479,
480,
481,
482,
483,
484,
485,
486,
487,
488,
489,
490,
491,
492,
493,
496,
497,
498,
499,
500,
501,
502,
503,
504,
505,
506,
507,
508,
509,
510,
511,
512,
513,
514,
515,
516,
517,
518,
536,
537,
538,
539,
540,
541,
542,
543,
556,
576,
596,
597,
598,
599,
600,
602,
603,
604,
606,
607,
608,
609,
616,
618,
636,
637,
638,
639,
640,
656,
657,
676,
696,
697,
698,
699,
700,
701,
702,
716,
717,
718,
719,
720,
721,
722,
736,
796,
797,
798,
799,
800,
801,
802,
803,
804,
805,
806,
807,
808,
809,
810,
811,
812,
813,
814,
815,
816,
817,
818,
819,
820,
821,
836,
837,
838,
839,
856,
876,
878,
879,
880,
881,
896,
916,
917,
918,
919,
920,
921,
922,
923,
924,
925,
926,
927,
928,
936,
956,
976,
977,
978,
979,
980,
981,
982,
983,
984,
985,
986,
987,
988,
989,
990,
991,
992,
996,
997,
998,
999,
1000,
1001,
1002,
1016,
1017,
1018,
1019,
1020,
1021,
1022,
1023,
1024,
1025,
1036,
1037,
1038,
1039,
1056,
1057,
1076,
1097,
1098,
1099,
1100,
1101,
1102,
1103,
1104,
1105,
1106,
1107,
1108,
1109,
1110,
1111,
1112,
1113,
1114,
1115,
1116,
1117,
1119,
1120,
1121,
1136,
1137,
1156,
1157,
1176,
1216,
1217,
1219,
1220,
1221,
1222,
1223,
1224,
1225,
1226,
1227,
1228,
1229,
1230,
1231,
1232,
1233,
1234,
1235,
1236,
1237,
1256,
1276,
1277,
1296,
1297,
1316,
1336,
1337,
1338,
1339,
1357,
1377,
1397,
1417,
1437,
1438,
1439,
1440,
1441,
1442,
1443,
1444,
1445,
1446,
1457,
1477,
1497,
1517,
1518,
1519,
1537,
1557,
1577,
1578,
1581,
1582,
1583,
1584,
1597,
1598,
1599,
1600,
1601,
1602,
1603,
1617,
1637,
1638,
1639,
1640,
1641,
1657,
1658,
1659,
1660,
1661,
1662,
1677,
1678,
1679,
1680,
1681,
1682,
1683,
1684,
1697,
1698,
1699,
1700,
1701,
1702,
1703,
1704,
1717,
1718,
1737,
1738,
1739,
1740,
1741,
1742,
1757,
1758,
1759,
1760,
1761,
1762,
1763,
1764,
1765,
1766,
1767,
1768,
1769,
1770,
1771,
1777,
1778,
1779,
1780,
1797,
1798,
1817,
1837,
1857,
1858,
1877,
1878,
1879,
1880,
1881,
1882,
1883,
1884,
1885,
1886,
1887,
1897,
1898,
1917,
1937,
1938,
1939,
1940,
1941,
1942,
1943,
1957,
1958,
1959,
1977,
1978,
1997,
1998,
2017,
2037,
2057,
2077,
2078,
2079,
2097,
2098,
2099,
2100,
2101,
2102,
2103,
2104,
2117,
2118,
2119,
2137,
2138,
2157,
2158,
2159,
2160,
2161,
2177,
2197,
2198,
2217,
2237,
2238,
2239,
2240,
2241,
2241,
2242,
2243,
2244,
2245,
2246,
2247,
2248,
2249,
2250,
2251,
2252,
2253,
2254,
2255,
2256,
2257,
2258,
2259,
2260,
2261,
2262,
2263,
2264,
2265,
2266,
2267,
2268,
2269,
2270,
2271,
2272,
2273,
2274,
2275,
2276,
2277,
2278,
2279,
2280,
2297,
2298,
2299,
2300,
2301,
2302,
2303,
2317,
2318,
2319,
2320,
2321,
2322,
2323,
2324,
2325,
2326,
2337,
2338,
2339,
2357,
2358,
2359,
2360,
2361,
2362,
2363,
2364,
2365,
2366,
2367,
2368,
2369,
2370,
2371,
2372,
2373,
2374,
2375,
2376,
2377,
2378,
2379,
2397,
2398,
2399,
2400,
2401,
2402,
2403,
2404,
2405,
2406,
2407,
2408,
2417,
2418,
2419,
2420,
2421,
2437,
2457,
2477,
2478,
2479,
2480,
2481,
2497,
2517,
2518,
2519,
2520,
2521,
2522,
2537,
2538,
2539,
2540,
2541,
2557,
2558,
2559,
2560,
2561,
2562,
2563,
2577,
2597,
2617,
2618,
2619,
2620,
2621,
2622,
2623,
2624,
2625,
2626,
2627,
2637,
2657,
2677,
2697,
2717,
2737,
2738,
2739,
2740,
2741,
2742,
2743,
2744,
2757,
2777,
2797,
2837,
2838,
2839,
2857,
2877,
2897,
2917,
2918,
2937,
2938,
2957,
2958,
2959,
2960,
2961,
2962,
2963,
2964,
2977,
2978,
2979,
3017,
3037,
3038,
3039,
3057,
3058,
3077,
3097,
3098,
3099,
3100,
3117,
3137,
3138,
3139,
3140,
3157,
3177,
3197,
3217,
3237,
3257,
3277,
3297,
3298,
3299,
3300,
3301,
3302,
3303,
3304,
3305,
3306,
3317,
3318,
3319,
3320,
3321,
3337,
3338,
3357,
3358,
3377,
3378,
3379,
3380,
3381,
3382,
3383,
3384,
3397,
3398,
3417,
3418,
3419,
3420,
3421,
3422,
3423,
3424,
3425,
3426,
3427,
3428,
3429,
3430,
3431,
3432,
3433,
3434,
3435,
3436,
3437,
3438,
3439,
3440,
3441,
3442,
3443,
3444,
3445,
3446,
3447,
3448,
3449,
3450,
3451,
3452,
3453,
3454,
3455,
3456,
3457,
3460,
3461,
3462,
3463,
3464,
3465,
3466,
3467,
3468,
3469,
3470,
3471,
3472,
3473,
3474,
3475,
3476,
3477,
3478,
3479,
3480,
3481,
3482,
3483,
3484,
3485,
3486,
3487,
3488,
3489,
3490,
3491,
3492,
3493,
3494,
3495,
3496,
3497,
3498,
3499,
3500,
3501,
3502,
3503,
3504,
3505,
3506,
3507,
3508,
3509,
3510,
3511,
3512,
3513,
3514,
3515,
3516,
3517,
3518,
3519,
3520,
3521,
3522,
3523,
3524,
3525,
3526,
3527,
3528,
3529,
3530,
3531,
3532,
3533,
3534,
3535,
3536,
3537,
3538,
3539,
3540,
3541,
3542,
3543,
3544,
3545,
3546,
3547,
3548,
3549,
3550,
3551,
3552,
3553,
3554,
3555,
3556,
3557,
3558,
3559,
3560,
3561,
3562,
3563,
3564,
3565,
3566,
3567,
3568,
3569,
3570,
3571,
3572,
3573,
3574,
3575,
3576,
3577,
3578,
3579,
3580,
3581,
3582,
3583,
3584,
3585,
3586,
3587,
3588,
3589,
3590,
3591,
3592,
3593,
3594,
3595,
3596,
3597,
3598,
3599,
3600,
3601,
3602,
3603,
3604,
3605,
3606,
3607,
3608,
3610,
3611,
3612,
3613,
3614,
3615,
3616,
3617,
3618,
3619,
3620,
3621,
3622,
3623,
3624,
3625,
3626,
3627,
3628,
3629,
3630,
3631,
3632,
3633,
3634,
3636,
3637,
3638,
3639,
3640,
3641,
3642,
3643,
3644,
3645,
3646,
3647,
3648,
3649,
3650,
3651,
3652,
3653,
3654,
3655,
3656,
3657,
3658,
3659,
3660,
3661,
3662,
3663,
3664,
3665,
3666,
3667,
3668,
3669,
3670,
3671,
3672,
3673,
3674,
3675,
3676,
3677,
3678,
3679,
3680,
3681,
3682,
3683,
3684,
3685,
3686,
3687,
3688,
3689,
3690,
3691,
3692,
3693,
3694,
3695,
3696,
3697,
3698,
3699,
3700,
3701,
3702,
3703,
3704,
3705,
3706,
3707,
3708,
3709,
3710,
3711,
5237,
3713,
3714,
3715,
3716,
3717,
3718,
3719,
3720,
3721,
3722,
3723,
3724,
3725,
3726,
3727,
3728,
3729,
3730,
3731,
3732,
3733,
3734,
3735,
3736,
3737,
3738,
3739,
3740,
3741,
3742,
3743,
3744,
3745,
3746,
3747,
3748,
3749,
3750,
3751,
3752,
3753,
3754,
3755,
3756,
3757,
3758,
3759,
3760,
3761,
3762,
3763,
3764,
3765,
3766,
3767,
3768,
3769,
3770,
3771,
3772,
3773,
3774,
3775,
3776,
3777,
3778,
3779,
3780,
3781,
3782,
3783,
3784,
3785,
3786,
3787,
3788,
3789,
3790,
3791,
3792,
3793,
3794,
3795,
3796,
3797,
3798,
3799,
3800,
3801,
3802,
3803,
3804,
3805,
3806,
3807,
3808,
3809,
3810,
3811,
3812,
3813,
3814,
3815,
3816,
3817,
3818,
3819,
3820,
3821,
3822,
3823,
3824,
3825,
3826,
3827,
3828,
3829,
3830,
3831,
3832,
3833,
3834,
3835,
3836,
3837,
3838,
3839,
3840,
3841,
3842,
3844,
3845,
3846,
3847,
3848,
3849,
3850,
3851,
3852,
3854,
3855,
3856,
3857,
3858,
3859,
3860,
3861,
3862,
3863,
3864,
3865,
3866,
3867,
3868,
3869,
3870,
3871,
3872,
3873,
3874,
3875,
3876,
3877,
3878,
3879,
3880,
3881,
3882,
3883,
3884,
3885,
3886,
3887,
3888,
3889,
3890,
3891,
3892,
3893,
3894,
3895,
3896,
3897,
3898,
3899,
3900,
3901,
3902,
3903,
3904,
3905,
3906,
3907,
3908,
3909,
3910,
3911,
3912,
3913,
3914,
3915,
3916,
3917,
3918,
3919,
3920,
3921,
3922,
3923,
3924,
3925,
3926,
3927,
3928,
3929,
3930,
3931,
3932,
3933,
3934,
3935,
3936,
3937,
3938,
3939,
3940,
3942,
3943,
3944,
3945,
3946,
3947,
3948,
3949,
3950,
3951,
3952,
3953,
3954,
3955,
3956,
3957,
};

char placesArray[2000][50] = {
"Dun Morogh                       ",
"Longshore                         "     ,
"Badlands                          "    ,
"Blasted Lands                     "         ,
"Blackwater Cove                   "           ,
"Swamp of Sorrows                  "            ,
"Northshire Valley                 "             ,
"Duskwood                          "    ,
"Wetlands                          "    ,
"Elwynn Forest                     "          ,
"The World Tree                    "           ,
"Durotar                           "    ,
"Dustwallow Marsh                  "             ,
"Azshara                           "    ,
"The Barrens                       "        ,
"Crystal Lake                      "         ,
"Zul'Gurub                         "      ,
"Moonbrook                         "      ,
"Kul Tiras                         "      ,
"Programmer Isle                   "            ,
"Northshire River                  "             ,
"Northshire Abbey                  "             ,
"Blackrock Mountain                "               ,
"Lighthouse                        "       ,
"Western Plaguelands               "                ,
"Nine                              " ,
"The Cemetary                      "         ,
"Stranglethorn Vale                "               ,
"Echo Ridge Mine                   "            ,
"Booty Bay                         "      ,
"Alterac Mountains                 "              ,
"Lake Nazferiti                    "           ,
"Loch Modan                        "       ,
"Westfall                          "     ,
"Deadwind Pass                     "          ,
"Darkshire                         "      ,
"Wild Shore                        "       ,
"Redridge Mountains                "               ,
"Arathi Highlands                  "             ,
"Burning Steppes                   "            ,
"The Hinterlands                   "            ,
"Dead Man's Hole                   "            ,
"Searing Gorge                     "          ,
"Thieves Camp                      "         ,
"Jasperlode Mine                   "            ,
"Valley of Heroes                  "             ,
"Heroes' Vigil                     "          ,
"Fargodeep Mine                    "           ,
"Northshire Vineyards              "                 ,
"Forest's Edge                     "          ,
"Thunder Falls                     "          ,
"Brackwell Pumpkin Patch           "                    ,
"The Stonefield Farm               "                ,
"The Maclure Vineyards             "                  ,
"Lake Everstill                    "           ,
"Lakeshire                         "      ,
"Stonewatch                        "       ,
"Stonewatch Falls                  "             ,
"The Dark Portal                   "            ,
"The Tainted Scar                  "             ,
"Pool of Tears                     "          ,
"Stonard                           "    ,
"Fallow Sanctuary                  "             ,
"Anvilmar                          "     ,
"Stormwind Mountains               "                ,
"Tirisfal Glades                   "            ,
"Stone Cairn Lake                  "             ,
"Goldshire                         "      ,
"Eastvale Logging Camp             "                  ,
"Mirror Lake Orchard               "                ,
"Tower of Azora                    "           ,
"Mirror Lake                       "        ,
"Vul'Gol Ogre Mound                "               ,
"Raven Hill                        "       ,
"Redridge Canyons                  "             ,
"Tower of Ilgalar                  "             ,
"Alther's Mill                     "          ,
"Rethban Caverns                   "            ,
"Rebel Camp                        "       ,
"Nesingwary's Expedition           "                    ,
"Kurzen's Compound                 "              ,
"Ruins of Zul'Kunda                "               ,
"Ruins of Zul'Mamwe                "               ,
"The Vile Reef                     "          ,
"Mosh'Ogg Ogre Mound               "                ,
"The Stockpile                     "          ,
"Saldean's Farm                    "           ,
"Sentinel Hill                     "          ,
"Furlbrow's Pumpkin Farm           "                    ,
"Jangolode Mine                    "           ,
"Gold Coast Quarry                 "              ,
"Westfall Lighthouse               "                ,
"Misty Valley                      "         ,
"Grom'gol Base Camp                "               ,
"Whelgar's Excavation Site         "                      ,
"Westbrook Garrison                "               ,
"Tranquil Gardens Cemetery         "                      ,
"Zuuldaia Ruins                    "           ,
"Bal'lal Ruins                     "          ,
"Kal'ai Ruins                      "         ,
"Tkashi Ruins                      "         ,
"Balia'mah Ruins                   "            ,
"Ziata'jai Ruins                   "            ,
"Mizjah Ruins                      "         ,
"Silverpine Forest                 "              ,
"Kharanos                          "     ,
"Coldridge Valley                  "             ,
"Gnomeregan                        "       ,
"Gol'Bolar Quarry                  "             ,
"Frostmane Hold                    "           ,
"The Grizzled Den                  "             ,
"Brewnall Village                  "             ,
"Misty Pine Refuge                 "              ,
"Eastern Plaguelands               "                ,
"Teldrassil                        "       ,
"Ironband's Excavation Site        "                       ,
"Mo'grosh Stronghold               "                ,
"Thelsamar                         "      ,
"Algaz Gate                        "       ,
"Stonewrought Dam                  "             ,
"The Farstrider Lodge              "                 ,
"Darkshore                         "      ,
"Silver Stream Mine                "               ,
"Menethil Harbor                   "            ,
"Designer Island                   "            ,
"The Bulwark                       "        ,
"Ruins of Lordaeron                "               ,
"Deathknell                        "       ,
"Night Web's Hollow                "               ,
"Solliden Farmstead                "               ,
"Agamand Mills                     "          ,
"Agamand Family Crypt              "                 ,
"Brill                             "  ,
"Whispering Gardens                "               ,
"Terrace of Repose                 "              ,
"Brightwater Lake                  "             ,
"Gunther's Retreat                 "              ,
"Garren's Haunt                    "           ,
"Balnir Farmstead                  "             ,
"Cold Hearth Manor                 "              ,
"Crusader Outpost                  "             ,
"The North Coast                   "            ,
"Whispering Shore                  "             ,
"Lordamere Lake                    "           ,
"Fenris Isle                       "        ,
"Faol's Rest                       "        ,
"Dolanaar                          "     ,
"Shadowglen                        "       ,
"Steelgrill's Depot                "               ,
"Hearthglen                        "       ,
"Northridge Lumber Camp            "                   ,
"Ruins of Andorhal                 "              ,
"School of Necromancy              "                 ,
"Uther's Tomb                      "         ,
"Sorrow Hill                       "        ,
"The Weeping Cave                  "             ,
"Felstone Field                    "           ,
"Dalson's Tears                    "           ,
"Gahrron's Withering               "                ,
"The Writhing Haunt                "               ,
"Mardenholde Keep                  "             ,
"Pyrewood Village                  "             ,
"Dun Modr                          "     ,
"The Great Sea                     "          ,
"Unused Ironcladcove               "                ,
"Shadowfang Keep                   "            ,
"Iceflow Lake                      "         ,
"Helm's Bed Lake                   "            ,
"Deep Elem Mine                    "           ,
"The Great Sea                     "          ,
"Mulgore                           "    ,
"Alexston Farmstead                "               ,
"Red Cloud Mesa                    "           ,
"Camp Narache                      "         ,
"Bloodhoof Village                 "              ,
"Stonebull Lake                    "           ,
"Ravaged Caravan                   "            ,
"Red Rocks                         "      ,
"The Skittering Dark               "                ,
"Valgan's Field                    "           ,
"The Sepulcher                     "          ,
"Olsen's Farthing                  "             ,
"The Greymane Wall                 "              ,
"Beren's Peril                     "          ,
"The Dawning Isles                 "              ,
"Ambermill                         "      ,
"Fenris Keep                       "        ,
"Shadowfang Keep                   "            ,
"The Decrepit Ferry                "               ,
"Malden's Orchard                  "             ,
"The Ivar Patch                    "           ,
"The Dead Field                    "           ,
"The Rotting Orchard               "                ,
"Brightwood Grove                  "             ,
"Forlorn Rowe                      "         ,
"The Whipple Estate                "               ,
"The Yorgen Farmstead              "                 ,
"The Cauldron                      "         ,
"Grimesilt Dig Site                "               ,
"Dreadmaul Rock                    "           ,
"Ruins of Thaurissan               "                ,
"Flame Crest                       "        ,
"Blackrock Stronghold              "                 ,
"The Pillar of Ash                 "              ,
"Blackrock Mountain                "               ,
"Altar of Storms                   "            ,
"Aldrassil                         "      ,
"Shadowthread Cave                 "              ,
"Fel Rock                          "     ,
"Lake Al'Ameth                     "          ,
"Starbreeze Village                "               ,
"Gnarlpine Hold                    "           ,
"Ban'ethil Barrow Den              "                 ,
"The Cleft                         "      ,
"The Oracle Glade                  "             ,
"Wellspring River                  "             ,
"Wellspring Lake                   "            ,
"Hillsbrad Foothills               "                ,
"Azshara Crater                    "           ,
"Dun Algaz                         "      ,
"Southshore                        "       ,
"Tarren Mill                       "        ,
"Durnholde Keep                    "           ,
"Stonewrought Pass                 "              ,
"The Foothill Caverns              "                 ,
"Lordamere Internment Camp         "                      ,
"Dalaran                           "    ,
"Strahnbrad                        "       ,
"Ruins of Alterac                  "             ,
"Crushridge Hold                   "            ,
"Slaughter Hollow                  "             ,
"The Uplands                       "        ,
"Southpoint Tower                  "             ,
"Hillsbrad Fields                  "             ,
"Hillsbrad                         "      ,
"Azurelode Mine                    "           ,
"Nethander Stead                   "            ,
"Dun Garok                         "      ,
"Thoradin's Wall                   "            ,
"Eastern Strand                    "           ,
"Western Strand                    "           ,
"Jaguero Isle                      "         ,
"Baradin Bay                       "        ,
"Menethil Bay                      "         ,
"Misty Reed Strand                 "              ,
"The Savage Coast                  "             ,
"The Crystal Shore                 "              ,
"Shell Beach                       "        ,
"North Tide's Run                  "             ,
"South Tide's Run                  "             ,
"The Overlook Cliffs               "                ,
"The Forbidding Sea                "               ,
"Ironbeard's Tomb                  "             ,
"Crystalvein Mine                  "             ,
"Ruins of Aboraz                   "            ,
"Janeiro's Point                   "            ,
"Northfold Manor                   "            ,
"Go'Shek Farm                      "         ,
"Dabyrie's Farmstead               "                ,
"Boulderfist Hall                  "             ,
"Witherbark Village                "               ,
"Drywhisker Gorge                  "             ,
"Refuge Pointe                     "          ,
"Hammerfall                        "       ,
"Blackwater Shipwrecks             "                  ,
"O'Breen's Camp                    "           ,
"Stromgarde Keep                   "            ,
"The Tower of Arathor              "                 ,
"The Sanctum                       "        ,
"Faldir's Cove                     "          ,
"The Drowned Reef                  "             ,
"Thandol Span                      "         ,
"Ashenvale                         "      ,
"The Great Sea                     "          ,
"Circle of East Binding            "                   ,
"Circle of West Binding            "                   ,
"Circle of Inner Binding           "                    ,
"Circle of Outer Binding           "                    ,
"Apocryphan's Rest                 "              ,
"Angor Fortress                    "           ,
"Lethlor Ravine                    "           ,
"Kargath                           "    ,
"Camp Kosh                         "      ,
"Camp Boff                         "      ,
"Camp Wurg                         "      ,
"Camp Cagg                         "      ,
"Agmond's End                      "         ,
"Hammertoe's Digsite               "                ,
"Dustbelch Grotto                  "             ,
"Aerie Peak                        "       ,
"Wildhammer Keep                   "            ,
"Quel'Danil Lodge                  "             ,
"Skulk Rock                        "       ,
"Zun'watha                         "      ,
"Shadra'Alor                       "        ,
"Jintha'Alor                       "        ,
"The Altar of Zul                  "             ,
"Seradane                          "     ,
"Feralas                           "    ,
"Brambleblade Ravine               "                ,
"Bael Modan                        "       ,
"The Venture Co. Mine              "                 ,
"Felwood                           "    ,
"Razor Hill                        "       ,
"Valley of Trials                  "             ,
"The Den                           "    ,
"Burning Blade Coven               "                ,
"Kolkar Crag                       "        ,
"Sen'jin Village                   "            ,
"Echo Isles                        "       ,
"Thunder Ridge                     "          ,
"Drygulch Ravine                   "            ,
"Dustwind Cave                     "          ,
"Tiragarde Keep                    "           ,
"Scuttle Coast                     "          ,
"Bladefist Bay                     "          ,
"Deadeye Shore                     "          ,
"Southfury River                   "            ,
"Camp Taurajo                      "         ,
"Far Watch Post                    "           ,
"The Crossroads                    "           ,
"Boulder Lode Mine                 "              ,
"The Sludge Fen                    "           ,
"The Dry Hills                     "          ,
"Dreadmist Peak                    "           ,
"Northwatch Hold                   "            ,
"The Forgotten Pools               "                ,
"Lushwater Oasis                   "            ,
"The Stagnant Oasis                "               ,
"Field of Giants                   "            ,
"The Merchant Coast                "               ,
"Ratchet                           "    ,
"Darkspear Strand                  "             ,
"Winterhoof Water Well             "                  ,
"Thunderhorn Water Well            "                   ,
"Wildmane Water Well               "                ,
"Skyline Ridge                     "          ,
"Thousand Needles                  "             ,
"The Tidus Stair                   "            ,
"Shady Rest Inn                    "           ,
"Bael'dun Digsite                  "             ,
"Desolace                          "     ,
"Stonetalon Mountains              "                 ,
"Gillijim's Isle                   "            ,
"Island of Doctor Lapidis          "                     ,
"Razorwind Canyon                  "             ,
"Bathran's Haunt                   "            ,
"The Ruins of Ordil'Aran           "                    ,
"Maestra's Post                    "           ,
"The Zoram Strand                  "             ,
"Astranaar                         "      ,
"The Shrine of Aessina             "                  ,
"Fire Scar Shrine                  "             ,
"The Ruins of Stardust             "                  ,
"The Howling Vale                  "             ,
"Silverwind Refuge                 "              ,
"Mystral Lake                      "         ,
"Fallen Sky Lake                   "            ,
"Iris Lake                         "      ,
"Moonwell                          "     ,
"Raynewood Retreat                 "              ,
"The Shady Nook                    "           ,
"Night Run                         "      ,
"Xavian                            "   ,
"Satyrnaar                         "      ,
"Splintertree Post                 "              ,
"The Dor'Danil Barrow Den          "                     ,
"Falfarren River                   "            ,
"Felfire Hill                      "         ,
"Demon Fall Canyon                 "              ,
"Demon Fall Ridge                  "             ,
"Warsong Lumber Camp               "                ,
"Bough Shadow                      "         ,
"The Shimmering Flats              "                 ,
"Tanaris                           "    ,
"Lake Falathim                     "          ,
"Auberdine                         "      ,
"Ruins of Mathystra                "               ,
"Tower of Althalaxx                "               ,
"Cliffspring Falls                 "              ,
"Bashal'Aran                       "        ,
"Ameth'Aran                        "       ,
"Grove of the Ancients             "                  ,
"The Master's Glaive               "                ,
"Remtravel's Excavation            "                   ,
"Mist's Edge                       "        ,
"The Long Wash                     "          ,
"Wildbend River                    "           ,
"Blackwood Den                     "          ,
"Cliffspring River                 "              ,
"The Veiled Sea                    "           ,
"Gold Road                         "      ,
"Scarlet Watch Post                "               ,
"Sun Rock Retreat                  "             ,
"Windshear Crag                    "           ,
"Cragpool Lake                     "          ,
"Mirkfallon Lake                   "            ,
"The Charred Vale                  "             ,
"Valley of the Bloodfuries         "                      ,
"Stonetalon Peak                   "            ,
"The Talon Den                     "          ,
"Greatwood Vale                    "           ,
"Brave Wind Mesa                   "            ,
"Fire Stone Mesa                   "            ,
"Mantle Rock                       "        ,
"Ruins of Jubuwal                  "             ,
"Pools of Arlithrien               "                ,
"The Rustmaul Dig Site             "                  ,
"Camp E'thok                       "        ,
"Splithoof Crag                    "           ,
"Highperch                         "      ,
"The Screeching Canyon             "                  ,
"Freewind Post                     "          ,
"The Great Lift                    "           ,
"Galak Hold                        "       ,
"Roguefeather Den                  "             ,
"The Weathered Nook                "               ,
"Thalanaar                         "      ,
"Un'Goro Crater                    "           ,
"Razorfen Kraul                    "           ,
"Raven Hill Cemetery               "                ,
"Moonglade                         "      ,
"Brackenwall Village               "                ,
"Swamplight Manor                  "             ,
"Bloodfen Burrow                   "            ,
"Darkmist Cavern                   "            ,
"Moggle Point                      "         ,
"Beezil's Wreck                    "           ,
"Witch Hill                        "       ,
"Sentry Point                      "         ,
"North Point Tower                 "              ,
"West Point Tower                  "             ,
"Lost Point                        "       ,
"Bluefen                           "    ,
"Stonemaul Ruins                   "            ,
"The Den of Flame                  "             ,
"The Dragonmurk                    "           ,
"Wyrmbog                           "    ,
"Onyxia's Lair                     "          ,
"Theramore Isle                    "           ,
"Foothold Citadel                  "             ,
"Ironclad Prison                   "            ,
"Dustwallow Bay                    "           ,
"Tidefury Cove                     "          ,
"Dreadmurk Shore                   "            ,
"Addle's Stead                     "          ,
"Fire Plume Ridge                  "             ,
"Lakkari Tar Pits                  "             ,
"Terror Run                        "       ,
"The Slithering Scar               "                ,
"Marshal's Refuge                  "             ,
"Fungal Rock                       "        ,
"Golakka Hot Springs               "                ,
"The Loch                          "     ,
"Beggar's Haunt                    "           ,
"Kodo Graveyard                    "           ,
"Ghost Walker Post                 "              ,
"Sar'theris Strand                 "              ,
"Thunder Axe Fortress              "                 ,
"Bolgan's Hole                     "          ,
"Mannoroc Coven                    "           ,
"Sargeron                          "     ,
"Magram Village                    "           ,
"Gelkis Village                    "           ,
"Valley of Spears                  "             ,
"Nijel's Point                     "          ,
"Kolkar Village                    "           ,
"Hyjal                             "  ,
"Winterspring                      "         ,
"Blackwolf River                   "            ,
"Kodo Rock                         "      ,
"Hidden Path                       "        ,
"Spirit Rock                       "        ,
"Shrine of the Dormant Flame       "                        ,
"Lake Elune'ara                    "           ,
"The Harborage                     "          ,
"Outland                           "    ,
"Craftsmen's Terrace               "                ,
"Tradesmen's Terrace               "                ,
"The Temple Gardens                "               ,
"Temple of Elune                   "            ,
"Cenarion Enclave                  "             ,
"Warrior's Terrace                 "              ,
"Rut'theran Village                "               ,
"Ironband's Compound               "                ,
"The Stockade                      "         ,
"Wailing Caverns                   "            ,
"Blackfathom Deeps                 "              ,
"Fray Island                       "        ,
"Gnomeregan                        "       ,
"Razorfen Downs                    "           ,
"Ban'ethil Hollow                  "             ,
"Scarlet Monastery                 "              ,
"Jerod's Landing                   "            ,
"Ridgepoint Tower                  "             ,
"The Darkened Bank                 "              ,
"Coldridge Pass                    "           ,
"Chill Breeze Valley               "                ,
"Shimmer Ridge                     "          ,
"Amberstill Ranch                  "             ,
"The Tundrid Hills                 "              ,
"South Gate Pass                   "            ,
"South Gate Outpost                "               ,
"North Gate Pass                   "            ,
"North Gate Outpost                "               ,
"Gates of Ironforge                "               ,
"Stillwater Pond                   "            ,
"Nightmare Vale                    "           ,
"Venomweb Vale                     "          ,
"The Bulwark                       "        ,
"Southfury River                   "            ,
"Southfury River                   "            ,
"Razormane Grounds                 "              ,
"Skull Rock                        "       ,
"Palemane Rock                     "          ,
"Windfury Ridge                    "           ,
"The Golden Plains                 "              ,
"The Rolling Plains                "               ,
"Dun Algaz                         "      ,
"Dun Algaz                         "      ,
"North Gate Pass                   "            ,
"South Gate Pass                   "            ,
"Twilight Grove                    "           ,
"GM Island                         "      ,
"Southfury River                   "            ,
"Southfury River                   "            ,
"Thandol Span                      "         ,
"Thandol Span                      "         ,
"Purgation Isle                    "           ,
"The Jansen Stead                  "             ,
"The Dead Acre                     "          ,
"The Molsen Farm                   "            ,
"Stendel's Pond                    "           ,
"The Dagger Hills                  "             ,
"Demont's Place                    "           ,
"The Dust Plains                   "            ,
"Stonesplinter Valley              "                 ,
"Valley of Kings                   "            ,
"Algaz Station                     "          ,
"Bucklebree Farm                   "            ,
"The Shining Strand                "               ,
"North Tide's Hollow               "                ,
"Grizzlepaw Ridge                  "             ,
"The Verdant Fields                "               ,
"Gadgetzan                         "      ,
"Steamwheedle Port                 "              ,
"Zul'Farrak                        "       ,
"Sandsorrow Watch                  "             ,
"Thistleshrub Valley               "                ,
"The Gaping Chasm                  "             ,
"The Noxious Lair                  "             ,
"Dunemaul Compound                 "              ,
"Eastmoon Ruins                    "           ,
"Waterspring Field                 "              ,
"Zalashji's Den                    "           ,
"Land's End Beach                  "             ,
"Wavestrider Beach                 "              ,
"Uldum                             "  ,
"Valley of the Watchers            "                   ,
"Gunstan's Post                    "           ,
"Southmoon Ruins                   "            ,
"Render's Camp                     "          ,
"Render's Valley                   "            ,
"Render's Rock                     "          ,
"Stonewatch Tower                  "             ,
"Galardell Valley                  "             ,
"Lakeridge Highway                 "              ,
"Three Corners                     "          ,
"Direforge Hill                    "           ,
"Raptor Ridge                      "         ,
"Black Channel Marsh               "                ,
"The Green Belt                    "           ,
"Mosshide Fen                      "         ,
"Thelgen Rock                      "         ,
"Bluegill Marsh                    "           ,
"Saltspray Glen                    "           ,
"Sundown Marsh                     "          ,
"The Green Belt                    "           ,
"Angerfang Encampment              "                 ,
"Grim Batol                        "       ,
"Dragonmaw Gates                   "            ,
"The Lost Fleet                    "           ,
"Darrow Hill                       "        ,
"Thoradin's Wall                   "            ,
"Webwinder Path                    "           ,
"The Hushed Bank                   "            ,
"Manor Mistmantle                  "             ,
"Camp Mojache                      "         ,
"Grimtotem Compound                "               ,
"The Writhing Deep                 "              ,
"Wildwind Lake                     "          ,
"Gordunni Outpost                  "             ,
"Mok'Gordun                        "       ,
"Feral Scar Vale                   "            ,
"Frayfeather Highlands             "                  ,
"Idlewind Lake                     "          ,
"The Forgotten Coast               "                ,
"East Pillar                       "        ,
"West Pillar                       "        ,
"Dream Bough                       "        ,
"Jademir Lake                      "         ,
"Oneiros                           "    ,
"Ruins of Ravenwind                "               ,
"Rage Scar Hold                    "           ,
"Feathermoon Stronghold            "                   ,
"Ruins of Solarsal                 "              ,
"The Twin Colossals                "               ,
"Sardor Isle                       "        ,
"Isle of Dread                     "          ,
"High Wilderness                   "            ,
"Lower Wilds                       "        ,
"Southern Barrens                  "             ,
"Southern Gold Road                "               ,
"Zul'Farrak                        "       ,
"Timbermaw Hold                    "           ,
"Vanndir Encampment                "               ,
"Legash Encampment                 "              ,
"Thalassian Base Camp              "                 ,
"Ruins of Eldarath                 "              ,
"Hetaera's Clutch                  "             ,
"Temple of Zin-Malor               "                ,
"Bear's Head                       "        ,
"Ursolan                           "    ,
"Temple of Arkkoran                "               ,
"Bay of Storms                     "          ,
"The Shattered Strand              "                 ,
"Tower of Eldara                   "            ,
"Jagged Reef                       "        ,
"Southridge Beach                  "             ,
"Ravencrest Monument               "                ,
"Forlorn Ridge                     "          ,
"Lake Mennar                       "        ,
"Shadowsong Shrine                 "              ,
"Haldarr Encampment                "               ,
"Valormok                          "     ,
"The Ruined Reaches                "               ,
"The Talondeep Path                "               ,
"The Talondeep Path                "               ,
"Rocktusk Farm                     "          ,
"Jaggedswine Farm                  "             ,
"Razorfen Downs                    "           ,
"Lost Rigger Cove                  "             ,
"Uldaman                           "    ,
"Lordamere Lake                    "           ,
"Lordamere Lake                    "           ,
"Gallows' Corner                   "            ,
"Silithus                          "     ,
"Emerald Forest                    "           ,
"Sunken Temple                     "          ,
"Dreadmaul Hold                    "           ,
"Nethergarde Keep                  "             ,
"Dreadmaul Post                    "           ,
"Serpent's Coil                    "           ,
"Altar of Storms                   "            ,
"Firewatch Ridge                   "            ,
"The Slag Pit                      "         ,
"The Sea of Cinders                "               ,
"Blackrock Mountain                "               ,
"Thorium Point                     "          ,
"Garrison Armory                   "            ,
"The Temple of Atal'Hakkar         "                      ,
"Undercity                         "      ,
"Uldaman                           "    ,
"Not Used Deadmines                "               ,
"Stormwind City                    "           ,
"Ironforge                         "      ,
"Splithoof Hold                    "           ,
"The Cape of Stranglethorn         "                      ,
"Southern Savage Coast             "                  ,
"Unused The Deadmines              "                  ,
"Unused Ironclad Cove              "                  ,
"The Deadmines                     "          ,
"Ironclad Cove                     "          ,
"Blackrock Spire                   "            ,
"Blackrock Depths                  "             ,
"Raptor Grounds UNUSED             "                  ,
"Grol'dom Farm UNUSED              "                 ,
"Mor'shan Base Camp                "               ,
"Honor's Stand UNUSED              "                 ,
"Blackthorn Ridge UNUSED           "                    ,
"Bramblescar UNUSED                "               ,
"Agama'gor UNUSED                  "             ,
"Valley of Heroes                  "             ,
"Orgrimmar                         "      ,
"Thunder Bluff                     "          ,
"Elder Rise                        "       ,
"Spirit Rise                       "        ,
"Hunter Rise                       "        ,
"Darnassus                         "      ,
"Cenarion Enclave                  "             ,
"Craftsmen's Terrace               "                ,
"Warrior's Terrace                 "              ,
"The Temple Gardens                "               ,
"Tradesmen's Terrace               "                ,
"Gavin's Naze                      "         ,
"Sofera's Naze                     "          ,
"Corrahn's Dagger                  "             ,
"The Headland                      "         ,
"Misty Shore                       "        ,
"Dandred's Fold                    "           ,
"Growless Cave                     "          ,
"Chillwind Point                   "            ,
"Raptor Grounds                    "           ,
"Bramblescar                       "        ,
"Thorn Hill                        "       ,
"Agama'gor                         "      ,
"Blackthorn Ridge                  "             ,
"Honor's Stand                     "          ,
"The Mor'shan Rampart              "                 ,
"Grol'dom Farm                     "          ,
"Razorfen Kraul                    "           ,
"The Great Lift                    "           ,
"Mistvale Valley                   "            ,
"Nek'mani Wellspring               "                ,
"Bloodsail Compound                "               ,
"Venture Co. Base Camp             "                  ,
"Gurubashi Arena                   "            ,
"Spirit Den                        "       ,
"The Crimson Veil                  "             ,
"The Riptide                       "        ,
"The Damsel's Luck                 "              ,
"Venture Co. Operations Center     "                          ,
"Deadwood Village                  "             ,
"Felpaw Village                    "           ,
"Jaedenar                          "     ,
"Bloodvenom River                  "             ,
"Bloodvenom Falls                  "             ,
"Shatter Scar Vale                 "              ,
"Irontree Woods                    "           ,
"Irontree Cavern                   "            ,
"Timbermaw Hold                    "           ,
"Shadow Hold                       "        ,
"Shrine of the Deceiver            "                   ,
"Itharius's Cave                   "            ,
"Sorrowmurk                        "       ,
"Draenil'dur Village               "                ,
"Splinterspear Junction            "                   ,
"Stagalbog                         "      ,
"The Shifting Mire                 "              ,
"Stagalbog Cave                    "           ,
"Witherbark Caverns                "               ,
"Thoradin's Wall                   "            ,
"Boulder'gor                       "        ,
"Valley of Fangs                   "            ,
"The Dustbowl                      "         ,
"Mirage Flats                      "         ,
"Featherbeard's Hovel              "                 ,
"Shindigger's Camp                 "              ,
"Plaguemist Ravine                 "              ,
"Valorwind Lake                    "           ,
"Agol'watha                        "       ,
"Hiri'watha                        "       ,
"The Creeping Ruin                 "              ,
"Bogen's Ledge                     "          ,
"The Maker's Terrace               "                ,
"Dustwind Gulch                    "           ,
"Shaol'watha                       "        ,
"Noonshade Ruins                   "            ,
"Broken Pillar                     "          ,
"Abyssal Sands                     "          ,
"Southbreak Shore                  "             ,
"Caverns of Time                   "            ,
"The Marshlands                    "           ,
"Ironstone Plateau                 "              ,
"Blackchar Cave                    "           ,
"Tanner Camp                       "        ,
"Dustfire Valley                   "            ,
"Zul'Gurub                         "      ,
"Misty Reed Post                   "            ,
"Bloodvenom Post                   "            ,
"Talonbranch Glade                 "              ,
"Stratholme                        "       ,
"Quel'thalas                       "        ,
"Scholomance                       "        ,
"Twilight Vale                     "          ,
"Twilight Shore                    "           ,
"Alcaz Island                      "         ,
"Darkcloud Pinnacle                "               ,
"Dawning Wood Catacombs            "                   ,
"Stonewatch Keep                   "            ,
"Maraudon                          "     ,
"Stoutlager Inn                    "           ,
"Thunderbrew Distillery            "                   ,
"Menethil Keep                     "          ,
"Deepwater Tavern                  "             ,
"Shadow Grave                      "         ,
"Brill Town Hall                   "            ,
"Gallows' End Tavern               "                ,
"The Pools of Vision               "                ,
"Dreadmist Den                     "          ,
"Bael'dun Keep                     "          ,
"Emberstrife's Den                 "              ,
"Onyxia's Lair                     "          ,
"Windshear Mine                    "           ,
"Roland's Doom                     "          ,
"Battle Ring                       "        ,
"The Pools of Vision               "                ,
"Shadowbreak Ravine                "               ,
"Broken Spear Village              "                 ,
"Whitereach Post                   "            ,
"Gornia                            "   ,
"Zane's Eye Crater                 "              ,
"Mirage Raceway                    "           ,
"The Hidden Grove                  "             ,
"Timbermaw Post                    "           ,
"Winterfall Village                "               ,
"Mazthoril                         "      ,
"Frostfire Hot Springs             "                  ,
"Ice Thistle Hills                 "              ,
"Dun Mandarr                       "        ,
"Frostwhisper Gorge                "               ,
"Owl Wing Thicket                  "             ,
"Lake Kel'Theril                   "            ,
"The Ruins of Kel'Theril           "                    ,
"Starfall Village                  "             ,
"Ban'Thallow Barrow Den            "                   ,
"Everlook                          "     ,
"Darkwhisper Gorge                 "              ,
"Deeprun Tram                      "         ,
"The Fungal Vale                   "            ,
"The Marris Stead                  "             ,
"The Marris Stead                  "             ,
"The Undercroft                    "           ,
"Darrowshire                       "        ,
"Crown Guard Tower                 "              ,
"Corin's Crossing                  "             ,
"Scarlet Base Camp                 "              ,
"Tyr's Hand                        "       ,
"The Scarlet Basilica              "                 ,
"Light's Hope Chapel               "                ,
"Browman Mill                      "         ,
"The Noxious Glade                 "              ,
"Eastwall Tower                    "           ,
"Northdale                         "      ,
"Zul'Mashar                        "       ,
"Mazra'Alor                        "       ,
"Northpass Tower                   "            ,
"Quel'Lithien Lodge                "               ,
"Plaguewood                        "       ,
"Scourgehold                       "        ,
"Stratholme                        "       ,
"Stratholme                        "       ,
"Darrowmere Lake                   "            ,
"Caer Darrow                       "        ,
"Darrowmere Lake                   "            ,
"Caverns of Time                   "            ,
"Thistlefur Village                "               ,
"The Quagmire                      "         ,
"Windbreak Canyon                  "             ,
"South Seas                        "       ,
"The Great Sea                     "          ,
"The Great Sea                     "          ,
"The Great Sea                     "          ,
"The Great Sea                     "          ,
"The Veiled Sea                    "           ,
"The Veiled Sea                    "           ,
"The Veiled Sea                    "           ,
"The Veiled Sea                    "           ,
"The Veiled Sea                    "           ,
"Razor Hill Barracks               "                ,
"South Seas                        "       ,
"The Great Sea                     "          ,
"Bloodtooth Camp                   "            ,
"Forest Song                       "        ,
"Greenpaw Village                  "             ,
"Silverwing Outpost                "               ,
"Nighthaven                        "       ,
"Shrine of Remulos                 "              ,
"Stormrage Barrow Dens             "                  ,
"The Great Sea                     "          ,
"The Great Sea                     "          ,
"The Black Morass                  "             ,
"Old Hillsbrad Foothills           "                    ,
"Tarren Mill                       "        ,
"Southshore                        "       ,
"Durnholde Keep                    "           ,
"Dun Garok                         "      ,
"Hillsbrad Fields                  "             ,
"Eastern Strand                    "           ,
"Nethander Stead                   "            ,
"Darrow Hill                       "        ,
"Southpoint Tower                  "             ,
"Thoradin's Wall                   "            ,
"Western Strand                    "           ,
"Azurelode Mine                    "           ,
"The Great Sea                     "          ,
"The Great Sea                     "          ,
"The Great Sea                     "          ,
"The Forbidding Sea                "               ,
"The Forbidding Sea                "               ,
"The Forbidding Sea                "               ,
"The Forbidding Sea                "               ,
"Tethris Aran                      "         ,
"Ethel Rethor                      "         ,
"Ranazjar Isle                     "          ,
"Kormek's Hut                      "         ,
"Shadowprey Village                "               ,
"Blackrock Pass                    "           ,
"Morgan's Vigil                    "           ,
"Slither Rock                      "         ,
"Terror Wing Path                  "             ,
"Draco'dar                         "      ,
"Ragefire Chasm                    "           ,
"Nightsong Woods                   "            ,
"The Veiled Sea                    "           ,
"Morlos'Aran                       "        ,
"Emerald Sanctuary                 "              ,
"Jadefire Glen                     "          ,
"Ruins of Constellas               "                ,
"Bitter Reaches                    "           ,
"Rise of the Defiler               "                ,
"Lariss Pavilion                   "            ,
"Woodpaw Hills                     "          ,
"Woodpaw Den                       "        ,
"Verdantis River                   "            ,
"Ruins of Isildien                 "              ,
"Grimtotem Post                    "           ,
"Camp Aparaje                      "         ,
"Malaka'jin                        "       ,
"Boulderslide Ravine               "                ,
"Sishir Canyon                     "          ,
"Dire Maul                         "      ,
"Deadwind Ravine                   "            ,
"Diamondhead River                 "              ,
"Ariden's Camp                     "          ,
"The Vice                          "     ,
"Karazhan                          "     ,
"Morgan's Plot                     "          ,
"Dire Maul                         "      ,
"Alterac Valley                    "           ,
"Scrabblescrew's Camp              "                 ,
"Jadefire Run                      "         ,
"Thondroril River                  "             ,
"Thondroril River                  "             ,
"Lake Mereldar                     "          ,
"Pestilent Scar                    "           ,
"The Infectis Scar                 "              ,
"Blackwood Lake                    "           ,
"Eastwall Gate                     "          ,
"Terrorweb Tunnel                  "             ,
"Terrordale                        "       ,
"Kargathia Keep                    "           ,
"Valley of Bones                   "            ,
"Blackwing Lair                    "           ,
"Deadman's Crossing                "               ,
"Molten Core                       "        ,
"The Scarab Wall                   "            ,
"Southwind Village                 "              ,
"Twilight Base Camp                "               ,
"The Crystal Vale                  "             ,
"The Scarab Dais                   "            ,
"Hive'Ashi                         "      ,
"Hive'Zora                         "      ,
"Hive'Regal                        "       ,
"Shrine of the Fallen Warrior      "                         ,
"Alterac Valley                    "           ,
"Blackfathom Deeps                 "              ,
"The Master's Cellar               "                ,
"Stonewrought Pass                 "              ,
"Alterac Valley                    "           ,
"The Rumble Cage                   "            ,
"Chunk Test                        "       ,
"Zoram'gar Outpost                 "              ,
"Hall of Legends                   "            ,
"Champions' Hall                   "            ,
"Grosh'gok Compound                "               ,
"Sleeping Gorge                    "           ,
"Irondeep Mine                     "          ,
"Stonehearth Outpost               "                ,
"Dun Baldar                        "       ,
"Icewing Pass                      "         ,
"Frostwolf Village                 "              ,
"Tower Point                       "        ,
"Coldtooth Mine                    "           ,
"Winterax Hold                     "          ,
"Iceblood Garrison                 "              ,
"Frostwolf Keep                    "           ,
"Tor'kren Farm                     "          ,
"Frost Dagger Pass                 "              ,
"Ironstone Camp                    "           ,
"Weazel's Crater                   "            ,
"Tahonda Ruins                     "          ,
"Field of Strife                   "            ,
"Icewing Cavern                    "           ,
"Valor's Rest                      "         ,
"The Swarming Pillar               "                ,
"Twilight Post                     "          ,
"Twilight Outpost                  "             ,
"Ravaged Twilight Camp             "                  ,
"Shalzaru's Lair                   "            ,
"Talrendis Point                   "            ,
"Rethress Sanctum                  "             ,
"Moon Horror Den                   "            ,
"Scalebeard's Cave                 "              ,
"Boulderslide Cavern               "                ,
"Warsong Labor Camp                "               ,
"Chillwind Camp                    "           ,
"The Maul                          "     ,
"The Maul                          "     ,
"Bones of Grakkarond               "                ,
"Warsong Gulch                     "          ,
"Frostwolf Graveyard               "                ,
"Frostwolf Pass                    "           ,
"Dun Baldar Pass                   "            ,
"Iceblood Graveyard                "               ,
"Snowfall Graveyard                "               ,
"Stonehearth Graveyard             "                  ,
"Stormpike Graveyard               "                ,
"Icewing Bunker                    "           ,
"Stonehearth Bunker                "               ,
"Wildpaw Ridge                     "          ,
"Revantusk Village                 "              ,
"Rock of Durotan                   "            ,
"Silverwing Grove                  "             ,
"Warsong Lumber Mill               "                ,
"Silverwing Hold                   "            ,
"Wildpaw Cavern                    "           ,
"The Veiled Cleft                  "             ,
"Yojamba Isle                      "         ,
"Arathi Basin                      "         ,
"The Coil                          "     ,
"Altar of Hir'eek                  "             ,
"Shadra'zaar                       "        ,
"Hakkari Grounds                   "            ,
"Naze of Shirvallah                "               ,
"Temple of Bethekk                 "              ,
"The Bloodfire Pit                 "              ,
"Altar of the Blood God            "                   ,
"Zanza's Rise                      "         ,
"Edge of Madness                   "            ,
"Trollbane Hall                    "           ,
"Defiler's Den                     "          ,
"Pagle's Pointe                    "           ,
"Farm                              " ,
"Blacksmith                        "       ,
"Lumber Mill                       "        ,
"Gold Mine                         "      ,
"Stables                           "    ,
"Cenarion Hold                     "          ,
"Staghelm Point                    "           ,
"Bronzebeard Encampment            "                   ,
"Ahn'Qiraj                         "      ,
"Ruins of Ahn'Qiraj                "               ,
"Eversong Woods                    "           ,
"Sunstrider Isle                   "            ,
"Shrine of Dath'Remar              "                 ,
"Ghostlands                        "       ,
"Scarab Terrace                    "           ,
"General's Terrace                 "              ,
"The Reservoir                     "          ,
"The Hatchery                      "         ,
"The Comb                          "     ,
"Watchers' Terrace                 "              ,
"Scarab Terrace                    "           ,
"General's Terrace                 "              ,
"The Reservoir                     "          ,
"The Hatchery                      "         ,
"The Comb                          "     ,
"Watchers' Terrace                 "              ,
"Twilight's Run                    "           ,
"Ortell's Hideout                  "             ,
"Scarab Terrace                    "           ,
"General's Terrace                 "              ,
"The Reservoir                     "          ,
"The Hatchery                      "         ,
"The Comb                          "     ,
"Watchers' Terrace                 "              ,
"Ruins of Ahn'Qiraj                "               ,
"The North Sea                     "          ,
"Naxxramas                         "      ,
"Karazhan                          "     ,
"Golden Strand                     "          ,
"Sunsail Anchorage                 "              ,
"Fairbreeze Village                "               ,
"Magisters Gate                    "           ,
"Farstrider Retreat                "               ,
"North Sanctum                     "          ,
"West Sanctum                      "         ,
"East Sanctum                      "         ,
"Saltheril's Haven                 "              ,
"Thuron's Livery                   "            ,
"Stillwhisper Pond                 "              ,
"The Living Wood                   "            ,
"Azurebreeze Coast                 "              ,
"Lake Elrendar                     "          ,
"The Scorched Grove                "               ,
"Zeb'Watha                         "      ,
"Tor'Watha                         "      ,
"Karazhan                          "     ,
"Gates of Ahn'Qiraj                "               ,
"The Veiled Sea                    "           ,
"Duskwither Grounds                "               ,
"Duskwither Spire                  "             ,
"The Dead Scar                     "          ,
"Hellfire Peninsula                "               ,
"The Sunspire                      "         ,
"Falthrien Academy                 "              ,
"Ravenholdt Manor                  "             ,
"Silvermoon City                   "            ,
"Tranquillien                      "         ,
"Suncrown Village                  "             ,
"Goldenmist Village                "               ,
"Windrunner Village                "               ,
"Windrunner Spire                  "             ,
"Sanctum of the Sun                "               ,
"Sanctum of the Moon               "                ,
"Dawnstar Spire                    "           ,
"Farstrider Enclave                "               ,
"An'daroth                         "      ,
"An'telas                          "     ,
"An'owyn                           "    ,
"Deatholme                         "      ,
"Bleeding Ziggurat                 "              ,
"Howling Ziggurat                  "             ,
"Shalandis Isle                    "           ,
"Toryl Estate                      "         ,
"Underlight Mines                  "             ,
"Andilien Estate                   "            ,
"Hatchet Hills                     "          ,
"Amani Pass                        "       ,
"Sungraze Peak                     "          ,
"Amani Catacombs                   "            ,
"Tower of the Damned               "                ,
"Zeb'Sora                          "     ,
"Lake Elrendar                     "          ,
"The Dead Scar                     "          ,
"Elrendar River                    "           ,
"Zeb'Tela                          "     ,
"Zeb'Nowa                          "     ,
"Nagrand                           "    ,
"Terokkar Forest                   "            ,
"Shadowmoon Valley                 "              ,
"Zangarmarsh                       "        ,
"Blade's Edge Mountains            "                   ,
"Netherstorm                       "        ,
"Azuremyst Isle                    "           ,
"Bloodmyst Isle                    "           ,
"Ammen Vale                        "       ,
"Crash Site                        "       ,
"Silverline Lake                   "            ,
"Nestlewood Thicket                "               ,
"Shadow Ridge                      "         ,
"Skulking Row                      "         ,
"Dawning Lane                      "         ,
"Ruins of Silvermoon               "                ,
"Feth's Way                        "       ,
"Hellfire Citadel                  "             ,
"Thrallmar                         "      ,
"REUSE                             "  ,
"Honor Hold                        "       ,
"The Stair of Destiny              "                 ,
"Twisting Nether                   "            ,
"Forge Camp: Mageddon              "                 ,
"The Path of Glory                 "              ,
"The Great Fissure                 "              ,
"Plain of Shards                   "            ,
"Hellfire Citadel                  "             ,
"Expedition Armory                 "              ,
"Throne of Kil'jaeden              "                 ,
"Forge Camp: Rage                  "             ,
"Invasion Point: Annihilator       "                        ,
"Borune Ruins                      "         ,
"Ruins of Sha'naar                 "              ,
"Temple of Telhamat                "               ,
"Pools of Aggonar                  "             ,
"Falcon Watch                      "         ,
"Mag'har Post                      "         ,
"Den of Haal'esh                   "            ,
"The Exodar                        "       ,
"Elrendar Falls                    "           ,
"Nestlewood Hills                  "             ,
"Ammen Fields                      "         ,
"The Sacred Grove                  "             ,
"Hellfire Ramparts                 "              ,
"Hellfire Citadel                  "             ,
"Emberglade                        "       ,
"Cenarion Refuge                   "            ,
"Moonwing Den                      "         ,
"Pod Cluster                       "        ,
"Pod Wreckage                      "         ,
"Tides' Hollow                     "          ,
"Wrathscale Point                  "             ,
"Bristlelimb Village               "                ,
"Stillpine Hold                    "           ,
"Odesyus' Landing                  "             ,
"Valaar's Berth                    "           ,
"Silting Shore                     "          ,
"Azure Watch                       "        ,
"Geezle's Camp                     "          ,
"Menagerie Wreckage                "               ,
"Traitor's Cove                    "           ,
"Wildwind Peak                     "          ,
"Wildwind Path                     "          ,
"Zeth'Gor                          "     ,
"Beryl Coast                       "        ,
"Blood Watch                       "        ,
"Bladewood                         "      ,
"The Vector Coil                   "            ,
"The Warp Piston                   "            ,
"The Cryo-Core                     "          ,
"The Crimson Reach                 "              ,
"Wrathscale Lair                   "            ,
"Ruins of Loreth'Aran              "                 ,
"Nazzivian                         "      ,
"Axxarien                          "     ,
"Blacksilt Shore                   "            ,
"The Foul Pool                     "          ,
"The Hidden Reef                   "            ,
"Amberweb Pass                     "          ,
"Wyrmscar Island                   "            ,
"Talon Stand                       "        ,
"Bristlelimb Enclave               "                ,
"Ragefeather Ridge                 "              ,
"Kessel's Crossing                 "              ,
"Tel'athion's Camp                 "              ,
"The Bloodcursed Reef              "                 ,
"Hyjal Past                        "       ,
"Hyjal Summit                      "         ,
"Coilfang Reservoir                "               ,
"Vindicator's Rest                 "              ,
"Burning Blade Ruins               "                ,
"Clan Watch                        "       ,
"Bloodcurse Isle                   "            ,
"Garadar                           "    ,
"Skysong Lake                      "         ,
"Throne of the Elements            "                   ,
"Laughing Skull Ruins              "                 ,
"Warmaul Hill                      "         ,
"Gruul's Lair                      "         ,
"Auren Ridge                       "        ,
"Auren Falls                       "        ,
"Lake Sunspring                    "           ,
"Sunspring Post                    "           ,
"Aeris Landing                     "          ,
"Forge Camp: Fear                  "             ,
"Forge Camp: Hate                  "             ,
"Telaar                            "   ,
"Northwind Cleft                   "            ,
"Halaa                             "  ,
"Southwind Cleft                   "            ,
"Oshu'gun                          "     ,
"Spirit Fields                     "          ,
"Shamanar                          "     ,
"Ancestral Grounds                 "              ,
"Windyreed Village                 "              ,
"Elemental Plateau                 "              ,
"Kil'sorrow Fortress               "                ,
"The Ring of Trials                "               ,
"Silvermyst Isle                   "            ,
"Daggerfen Village                 "              ,
"Umbrafen Village                  "             ,
"Feralfen Village                  "             ,
"Bloodscale Enclave                "               ,
"Telredor                          "     ,
"Zabra'jin                         "      ,
"Quagg Ridge                       "        ,
"The Spawning Glen                 "              ,
"The Dead Mire                     "          ,
"Sporeggar                         "      ,
"Ango'rosh Grounds                 "              ,
"Ango'rosh Stronghold              "                 ,
"Funggor Cavern                    "           ,
"Serpent Lake                      "         ,
"The Drain                         "      ,
"Umbrafen Lake                     "          ,
"Marshlight Lake                   "            ,
"Portal Clearing                   "            ,
"Sporewind Lake                    "           ,
"The Lagoon                        "       ,
"Blades' Run                       "        ,
"Blade Tooth Canyon                "               ,
"Commons Hall                      "         ,
"Derelict Manor                    "           ,
"Huntress of the Sun               "                ,
"Falconwing Square                 "              ,
"Halaani Basin                     "          ,
"Hewn Bog                          "     ,
"Boha'mu Ruins                     "          ,
"The Stadium                       "        ,
"The Overlook                      "         ,
"Broken Hill                       "        ,
"Mag'hari Procession               "                ,
"Nesingwary Safari                 "              ,
"Cenarion Thicket                  "             ,
"Tuurem                            "   ,
"Veil Shienor                      "         ,
"Veil Skith                        "       ,
"Veil Shalas                       "        ,
"Skettis                           "    ,
"Blackwind Valley                  "             ,
"Firewing Point                    "           ,
"Grangol'var Village               "                ,
"Stonebreaker Hold                 "              ,
"Allerian Stronghold               "                ,
"Bonechewer Ruins                  "             ,
"Veil Lithic                       "        ,
"Olembas                           "    ,
"Auchindoun                        "       ,
"Veil Reskk                        "       ,
"Blackwind Lake                    "           ,
"Lake Ere'Noru                     "          ,
"Lake Jorune                       "        ,
"Skethyl Mountains                 "              ,
"Misty Ridge                       "        ,
"The Broken Hills                  "             ,
"The Barrier Hills                 "              ,
"The Bone Wastes                   "            ,
"Nagrand Arena                     "          ,
"Laughing Skull Courtyard          "                     ,
"The Ring of Blood                 "              ,
"Arena Floor                       "        ,
"Blade's Edge Arena                "               ,
"Shattrath City                    "           ,
"The Shepherd's Gate               "                ,
"Telaari Basin                     "          ,
"The Dark Portal                   "            ,
"Alliance Base                     "          ,
"Horde Encampment                  "             ,
"Night Elf Village                 "              ,
"Nordrassil                        "       ,
"Black Temple                      "         ,
"Area                              "  ,
"The Blood Furnace                 "              ,
"The Shattered Halls               "                ,
"The Steamvault                    "           ,
"The Underbog                      "         ,
"The Slave Pens                    "           ,
"Swamprat Post                     "          ,
"Bleeding Hollow Ruins             "                  ,
"Twin Spire Ruins                  "             ,
"The Crumbling Waste               "                ,
"Manaforge Ara                     "          ,
"Arklon Ruins                      "         ,
"Cosmowrench                       "        ,
"Ruins of Enkaat                   "            ,
"Manaforge B'naar                  "             ,
"The Scrap Field                   "            ,
"The Vortex Fields                 "              ,
"The Heap                          "     ,
"Manaforge Coruu                   "            ,
"The Tempest Rift                  "             ,
"Kirin'Var Village                 "              ,
"The Violet Tower                  "             ,
"Manaforge Duro                    "           ,
"Voidwind Plateau                  "             ,
"Manaforge Ultris                  "             ,
"Celestial Ridge                   "            ,
"The Stormspire                    "           ,
"Forge Base: Oblivion              "                 ,
"Forge Base: Gehenna               "                ,
"Ruins of Farahlon                 "              ,
"Socrethar's Seat                  "             ,
"Legion Hold                       "        ,
"Shadowmoon Village                "               ,
"Wildhammer Stronghold             "                  ,
"The Hand of Gul'dan               "                ,
"The Fel Pits                      "         ,
"The Deathforge                    "           ,
"Coilskar Cistern                  "             ,
"Coilskar Point                    "           ,
"Sunfire Point                     "          ,
"Illidari Point                    "           ,
"Ruins of Baa'ri                   "            ,
"Altar of Sha'tar                  "             ,
"The Stair of Doom                 "              ,
"Ruins of Karabor                  "             ,
"Ata'mal Terrace                   "            ,
"Netherwing Fields                 "              ,
"Netherwing Ledge                  "             ,
"The Barrier Hills                 "              ,
"The High Path                     "          ,
"Windyreed Pass                    "           ,
"Zangar Ridge                      "         ,
"The Twilight Ridge                "               ,
"Razorthorn Trail                  "             ,
"Orebor Harborage                  "             ,
"Blades' Run                       "        ,
"Jagged Ridge                      "         ,
"Thunderlord Stronghold            "                   ,
"Blade Tooth Canyon                "               ,
"The Living Grove                  "             ,
"Sylvanaar                         "      ,
"Bladespire Hold                   "            ,
"Gruul's Lair                      "         ,
"Circle of Blood                   "            ,
"Bloodmaul Outpost                 "              ,
"Bloodmaul Camp                    "           ,
"Draenethyst Mine                  "             ,
"Trogma's Claim                    "           ,
"Blackwing Coven                   "            ,
"Grishnath                         "      ,
"Veil Lashh                        "       ,
"Veil Vekh                         "      ,
"Forge Camp: Terror                "               ,
"Forge Camp: Wrath                 "              ,
"Felstorm Point                    "           ,
"Forge Camp: Anger                 "              ,
"The Low Path                      "         ,
"Shadow Labyrinth                  "             ,
"Auchenai Crypts                   "            ,
"Sethekk Halls                     "          ,
"Mana-Tombs                        "       ,
"Felspark Ravine                   "            ,
"Valley of Bones                   "            ,
"Sha'naari Wastes                  "             ,
"The Warp Fields                   "            ,
"Fallen Sky Ridge                  "             ,
"Haal'eshi Gorge                   "            ,
"Stonewall Canyon                  "             ,
"Thornfang Hill                    "           ,
"Mag'har Grounds                   "            ,
"Void Ridge                        "       ,
"The Abyssal Shelf                 "              ,
"The Legion Front                  "             ,
"Zul'Aman                          "     ,
"Supply Caravan                    "           ,
"Reaver's Fall                     "          ,
"Cenarion Post                     "          ,
"Southern Rampart                  "             ,
"Northern Rampart                  "             ,
"Gor'gaz Outpost                   "            ,
"Spinebreaker Post                 "              ,
"The Path of Anguish               "                ,
"East Supply Caravan               "                ,
"Expedition Point                  "             ,
"Zeppelin Crash                    "           ,
"Testing                           "    ,
"Bloodscale Grounds                "               ,
"Darkcrest Enclave                 "              ,
"Eye of the Storm                  "             ,
"Warden's Cage                     "          ,
"Eclipse Point                     "          ,
"Isle of Tribulations              "                 ,
"Bloodmaul Ravine                  "             ,
"Dragons' End                      "         ,
"Daggermaw Canyon                  "             ,
"Vekhaar Stand                     "          ,
"Ruuan Weald                       "        ,
"Veil Ruuan                        "       ,
"Raven's Wood                      "         ,
"Death's Door                      "         ,
"Vortex Pinnacle                   "            ,
"Razor Ridge                       "        ,
"Ridge of Madness                  "             ,
"Dustquill Ravine                  "             ,
"Magtheridon's Lair                "               ,
"Sunfury Hold                      "         ,
"Spinebreaker Mountains            "                   ,
"Abandoned Armory                  "             ,
"The Black Temple                  "             ,
"Darkcrest Shore                   "            ,
"Tempest Keep                      "         ,
"Mok'Nathal Village                "               ,
"Tempest Keep                      "         ,
"The Arcatraz                      "         ,
"The Botanica                      "         ,
"The Arcatraz                      "         ,
"The Mechanar                      "         ,
"Netherstone                       "        ,
"Midrealm Post                     "          ,
"Tuluman's Landing                 "              ,
"Protectorate Watch Post           "                    ,
"Circle of Blood Arena             "                  ,
"Elrendar Crossing                 "              ,
"Ammen Ford                        "       ,
"Razorthorn Shelf                  "             ,
"Silmyr Lake                       "        ,
"Raastok Glade                     "          ,
"Thalassian Pass                   "            ,
"Churning Gulch                    "           ,
"Broken Wilds                      "         ,
"Bash'ir Landing                   "            ,
"Crystal Spine                     "          ,
"Skald                             "  ,
"Bladed Gulch                      "         ,
"Gyro-Plank Bridge                 "              ,
"Mage Tower                        "       ,
"Blood Elf Tower                   "            ,
"Draenei Ruins                     "          ,
"Fel Reaver Ruins                  "             ,
"The Proving Grounds               "                ,
"Eco-Dome Farfield                 "              ,
"Eco-Dome Skyperch                 "              ,
"Eco-Dome Sutheron                 "              ,
"Eco-Dome Midrealm                 "              ,
"Ethereum Staging Grounds          "                     ,
"Chapel Yard                       "        ,
"Access Shaft Zeon                 "              ,
"Trelleum Mine                     "          ,
"Invasion Point: Destroyer         "                      ,
"Camp of Boom                      "         ,
"Spinebreaker Pass                 "              ,
"Netherweb Ridge                   "            ,
"Derelict Caravan                  "             ,
"Refugee Caravan                   "            ,
"Shadow Tomb                       "        ,
"Veil Rhaze                        "       ,
"Tomb of Lights                    "           ,
"Carrion Hill                      "         ,
"Writhing Mound                    "           ,
"Ring of Observance                "               ,
"Auchenai Grounds                  "             ,
"Cenarion Watchpost                "               ,
"Aldor Rise                        "       ,
"Terrace of Light                  "             ,
"Scryer's Tier                     "          ,
"Lower City                        "       ,
"Invasion Point: Overlord          "                     ,
"Allerian Post                     "          ,
"Stonebreaker Camp                 "              ,
"Boulder'mok                       "        ,
"Cursed Hollow                     "          ,
"Coilfang Reservoir                "               ,
"The Bloodwash                     "          ,
"Veridian Point                    "           ,
"Middenvale                        "       ,
"The Lost Fold                     "          ,
"Mystwood                          "     ,
"Tranquil Shore                    "           ,
"Goldenbough Pass                  "             ,
"Runestone Falithas                "               ,
"Runestone Shan'dor                "               ,
"Fairbridge Strand                 "              ,
"Moongraze Woods                   "            ,
"Auchindoun                        "       ,
"Toshley's Station                 "              ,
"Singing Ridge                     "          ,
"Shatter Point                     "          ,
"Arklonis Ridge                    "           ,
"Bladespire Outpost                "               ,
"Gruul's Lair                      "         ,
"Northmaul Tower                   "            ,
"Southmaul Tower                   "            ,
"Shattered Plains                  "             ,
"Oronok's Farm                     "          ,
"The Altar of Damnation            "                   ,
"The Path of Conquest              "                 ,
"Eclipsion Fields                  "             ,
"Bladespire Grounds                "               ,
"Sketh'lon Base Camp               "                ,
"Sketh'lon Wreckage                "               ,
"Town Square                       "        ,
"Wizard Row                        "       ,
"Deathforge Tower                  "             ,
"Slag Watch                        "       ,
"Sanctum of the Stars              "                 ,
"Dragonmaw Fortress                "               ,
"The Fetid Pool                    "           ,
"Razaan's Landing                  "             ,
"Invasion Point: Cataclysm         "                      ,
"The Altar of Shadows              "                 ,
"Netherwing Pass                   "            ,
"Wayne's Refuge                    "           ,
"The Scalding Pools                "               ,
"Brian and Pat Test                "               ,
"Magma Fields                      "         ,
"Crimson Watch                     "          ,
"Evergrove                         "      ,
"Wyrmskull Bridge                  "             ,
"Scalewing Shelf                   "            ,
"Wyrmskull Tunnel                  "             ,
"Hellfire Basin                    "           ,
"The Shadow Stair                  "             ,
"Sha'tari Outpost                  "             ,
};


int main() 
{

	cout << "_________ Starting Classic WoW Game Presence by default _________" << endl << endl;
	DiscordEventHandlers handlers;
	memset(&handlers, 0, sizeof(handlers));
	Discord_Initialize("586804800168132608", &handlers, 1, "1234");
	int userInput = -1;
	while (userInput != 0) {

		cout << "|--- JUSTIN'S EZ RICH PRESENCE ---|" << endl;
		cout << "| 1.  Start a new rich presence   |" << endl;
		cout << "| 2.  Restart WoW rich presence   |" << endl;
		cout << "| 0.  Close                       |" << endl;
		cout << "|_________________________________|" << endl;

		startWowClassic();
		cin >> userInput;

		if (userInput == 1) {
			handleCustomPresence();
		}else if (userInput == 2) {
			cout << "Restarting WoW rich presence." << endl;
			startWowClassic();
		}else if (userInput == 0) {
			cout << "Thanks for using me! Bye-Bye DARLING!!!!" << endl;
			Discord_Shutdown();
		}else {
			cout << endl << "Try again you pepega." << endl << endl;
		}

	}
}

void startWowClassic()	{

	HWND hWnd = FindWindowA(0, "World of Warcraft");
	if (hWnd) {
		char playerDetails[60] = "Level ";

		DWORD PID;
		GetWindowThreadProcessId(hWnd, &PID);
		HANDLE hProc = OpenProcess(PROCESS_ALL_ACCESS, 0, PID);

		// get location  
		long long locationNumber = 0;
		ReadProcessMemory(hProc, (LPCVOID)locationOffset, &locationNumber, 2, NULL);
		string locationString = getLocationFromNumber(locationNumber);
		strcpy(currentLocation, locationString.c_str());

		// get class
		long long classIndicator = 0;
		ReadProcessMemory(hProc, (LPCVOID)(playerBase + classOffset), &classIndicator, 2, NULL);
		string classString = getClassFromNumber(classIndicator);
		strcpy(currentClass, classString.c_str());

		//get level
		long long classLevel = 0;
		ReadProcessMemory(hProc, (LPCVOID)(levelOffset), &classLevel, 2, NULL);
		string levelString = to_string(classLevel);
		strcpy(currentLevel, levelString.c_str());

		//get race
		long long raceIndicator = 0;
		ReadProcessMemory(hProc, (LPCVOID)(raceOffset), &raceIndicator, 2, NULL);
		string raceString = getRaceFromNumber(raceIndicator);
		strcpy(currentRace, raceString.c_str());
			   
		strcat(playerDetails, currentLevel);
		strcat(playerDetails, " ");
		strcat(playerDetails, currentRace);
		strcat(playerDetails, " ");
		strcat(playerDetails, currentClass);

		DiscordRichPresence discordPresence;
		memset(&discordPresence, 0, sizeof(discordPresence));
		discordPresence.state = playerDetails; // upper
		discordPresence.details = currentLocation; // lower
		discordPresence.startTimestamp = startTime;
		discordPresence.largeImageKey = "wowimage";
		discordPresence.partySize = 1;
		discordPresence.instance = 1;
		Discord_UpdatePresence(&discordPresence);

		while (1 != 0) {
			async(asynchronousUpdating);
			Sleep(3500);
		}

	}else {
		cout << "OH NO DARLING... WE CAN'T FIND THE GAME!!! :C" << endl;
		abort();
	}
}

void handleCustomPresence() {


	char state[50], details[50], imageName[50];

	cout << "Enter first line of text: " << endl;
	cin >> state;

	cout << "Enter second line of text: " << endl;
	cin >> details;

	cout << "Enter image key: (none == wow)" << endl;
	cin >> imageName;

	DiscordRichPresence discordPresence;
	memset(&discordPresence, 0, sizeof(discordPresence));
	discordPresence.state = state; // upper
	discordPresence.details = details; // lower
	discordPresence.startTimestamp = time(0);
	discordPresence.largeImageKey = imageName;
	discordPresence.partySize = 1;
	discordPresence.instance = 1;
	Discord_UpdatePresence(&discordPresence);

}

void asynchronousUpdating() {
		HWND hWnd = FindWindowA(0, "World of Warcraft");
		if (hWnd) {
			bool doesNeedUpdating = 0;
			char playerDetails[60] = "Level ";

			DWORD PID;
			GetWindowThreadProcessId(hWnd, &PID);
			HANDLE hProc = OpenProcess(PROCESS_ALL_ACCESS, 0, PID);

			// get location  
			long long locationNumber = 0;
			ReadProcessMemory(hProc, (LPCVOID)locationOffset, &locationNumber, 2, NULL);
			string locationString = getLocationFromNumber(locationNumber);

			if (strcmp(locationString.c_str(), currentLocation)) {
				strcpy(currentLocation, locationString.c_str());
				doesNeedUpdating = 1;
			}

			// get class
			long long classIndicator = 0;
			ReadProcessMemory(hProc, (LPCVOID)(playerBase + classOffset), &classIndicator, 2, NULL);
			string classString = getClassFromNumber(classIndicator);
			if (strcmp(classString.c_str(), currentClass)) {
				strcpy(currentClass, classString.c_str());
				doesNeedUpdating = 1;
			}

			//get level
			long long classLevel = 0;
			ReadProcessMemory(hProc, (LPCVOID)(levelOffset), &classLevel, 2, NULL);
			string levelString = to_string(classLevel);

			if (strcmp(levelString.c_str(), currentLevel)) {
				strcpy(currentLevel, levelString.c_str());
				doesNeedUpdating = 1;
			}

			//get race
			long long raceIndicator = 0;
			ReadProcessMemory(hProc, (LPCVOID)(raceOffset), &raceIndicator, 2, NULL);
			string raceString = getRaceFromNumber(raceIndicator);
			if (strcmp(raceString.c_str(), currentRace)) {
				strcpy(currentRace, raceString.c_str());
				doesNeedUpdating = 1;
			}

			strcat(playerDetails, currentLevel);
			strcat(playerDetails, " ");
			strcat(playerDetails, currentRace);
			strcat(playerDetails, " ");
			strcat(playerDetails, currentClass);

			if (doesNeedUpdating) {
				DiscordRichPresence discordPresence;
				memset(&discordPresence, 0, sizeof(discordPresence));
				discordPresence.state = playerDetails; // upper
				discordPresence.details = currentLocation; // lower
				discordPresence.startTimestamp = startTime;
				discordPresence.largeImageKey = "wowimage";
				discordPresence.partySize = 1;
				discordPresence.instance = 1;
				Discord_UpdatePresence(&discordPresence);
			}

		}
		else {
			cout << "OH NO DARLING... WE CAN'T FIND THE GAME!!! :C" << endl;
			abort();
		}
}


string getClassFromNumber(int i) {
	string classString;
	if (i == 1)
		classString = "Warrior";
	else if (i == 2)
		classString = "Paladin";
	else if (i == 3)
		classString = "Hunter";
	else if (i == 4)
		classString = "Rogue";
	else if (i == 5)
		classString = "Priest";
	else if (i == 7)
		classString = "Shaman";
	else if (i == 8)
		classString = "Mage";
	else if (i == 9)
		classString = "Warlock";
	else if (i == 11)
		classString = "Druid";

	return classString;
}

string getRaceFromNumber(int i) {
	string classString;

	if (i == 1)
		classString = "Human";
	else if (i == 2)
		classString = "Orc";
	else if (i == 3)
		classString = "Dwarf";
	else if (i == 4)
		classString = "Night Elf";
	else if (i == 5)
		classString = "Undead";
	else if (i == 6)
		classString = "Tauren";
	else if (i == 7)
		classString = "Gnome";
	else if (i == 8)
		classString = "Troll";


	return classString;
}
string getLocationFromNumber(int number) {
	string locationString;
	int index = -1;

	if (number == 1)
		return placesArray[0];


	for (int i = 0; i < 1563; i++) {
		if (indices[i] == number) {
			index = i;
			break;
		}
	}

	locationString = placesArray[index];

	return locationString;
}
